name = "feedback-intelligence"
main = "index.html"
compatibility_date = "2024-01-20"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.production.pages]
compatibility_flags = ["nodejs_compat"]
