name = "feedback-analysis"
main = "src/worker.js"
compatibility_date = "2025-01-20"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.production.pages]
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./" }

kv_namespaces = [
  { binding = "FEEDBACK", id = "feedback-kv" }
]
